version: '3.8'
services:
  reg-service:
    image: reg-service
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - microservice
    ports:
      - 8000:8000
    volumes:
      - spring:/app/
    depends_on:
      - db
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: regsystem
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: oros
    ports:
      - 41000:5432
    volumes:
        - dbdata:/var/lib/postgres/data
    networks:
      - microservice
  react:
    image: react-frontend
    build:
      context: src/main/frontend
      dockerfile: Dockerfile
    networks:
      - microservice
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - react:/app
      - '/app/node_modules'

  mailserver:
    image: maildev/maildev
    ports:
      - 1025:25
      - 1080:80
    networks:
      - microservice

volumes:
  dbdata:
    name: postgres_dbdata
  spring:
    name: spring_backend
  react:
    name: react_frontend

networks:
  microservice:
    name: microservice


